---
title: "Dull LMO"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
#libraries-----------------------------
library(tidyverse)
library(plotly)
library(crosstalk)
library(conflicted)
library(here)
library(sf)
library(tidytext)
conflicts_prefer(plotly::layout)
conflicts_prefer(dplyr::filter)
#constants------------------------------------
lmo_colours <- c("#8abbe8","#2a2d64")
#functions--------------------------------
get_current <- function(tbbl){
  tbbl$value[tbbl$name==min(tbbl$name)]
}
get_cagr <- function(tbbl){
  start <- tbbl$value[tbbl$name==min(tbbl$name)]
  end <- tbbl$value[tbbl$name==max(tbbl$name)]
  (end/start)^(1/(max(tbbl$name-min(tbbl$name))))-1
}
barplot_by <- function(tbbl, var, cat_order=NULL){
  plot_ly(tbbl,
        x = ~value,
        y = ~fct_reorder(get(var), value), 
        color = ~name,
        type = 'bar',
        orientation = 'h',
        hovertext = ~paste0(get(var),
                            "\n ",
                            name,
                            " = ",
                            scales::comma(value, accuracy = 1)),  
        hoverinfo = 'text',  
        textposition = "none")|> #hover only
  layout(
    legend = list(
      orientation = "h",   # Horizontal legend
      x = 0.5,             # Center the legend horizontally
      y = -.2,        # Place the legend below the plot
      xanchor = "center",  # Center the legend relative to the x position
      yanchor = "top"      # Align the top of the legend with the specified y position
    ),
    barmode = 'stack',
    yaxis = list(
      title = "",
      tickfont = list(size = 8),
      categoryorder = cat_order
      ),
    xaxis = list(
      title = "",
      tickformat = ","
    )
  )|>
  config(displayModeBar = FALSE)
}
barplot <- function(tbbl, var, yvar="two_digit", format=scales::comma, accuracy=1, tickformat=","){
  tbbl|>
    plot_ly(
          x = ~get(var),
          y = ~get(yvar), 
          type = 'bar',
          marker = list(color = lmo_colours[2]),
          orientation = 'h',
          hovertext = ~paste0(get(yvar),
                              "\n",
                              str_to_title(str_replace_all(var, "_"," ")),
                              " = ",
                              format(get(var), accuracy = accuracy)),  
          hoverinfo = 'text',  
          textposition = "none")|> #hover only
    layout(
      showlegend = FALSE,
      yaxis = list(
        title = "",
        tickfont = list(size = 8),
        categoryorder = "trace"
        ),
      xaxis = list(
        title = "",
        tickformat = tickformat
      )
    )  
}
#read the data-----------------------------
demand_occ <- read_rds(here("out","demand_occ.rds"))
#demand_ind <- read_rds(here("out","demand_ind.rds"))

#shareddata objects for job openings by occupation------------------------------------
shared_for_pie <- demand_occ|>
  group_by(name, geographic_area)|>
  summarize(value=sum(value, na.rm = TRUE))|>
  SharedData$new(~geographic_area, group="region1")

shared_broad <- demand_occ|>
  group_by(broad, geographic_area, name)|>
  summarize(value=sum(value, na.rm=TRUE),
            `Job Openings`=sum(`Job Openings`, na.rm = TRUE))|>
  ungroup()|>
  arrange(geographic_area, `Job Openings`)|>
  SharedData$new(~geographic_area, group="region1")

shared_teer <- demand_occ|>
  group_by(teer, geographic_area, name)|>
  summarize(value=sum(value, na.rm=TRUE),
            `Job Openings`=sum(`Job Openings`, na.rm = TRUE))|>
  ungroup()|>
  arrange(geographic_area, `Job Openings`)|>
  SharedData$new(~geographic_area, group="region1")

shared_two <- demand_occ|>
  group_by(geographic_area, teer, broad, name)|>
  summarize(value=sum(value, na.rm=TRUE),
            `Job Openings`=sum(`Job Openings`, na.rm = TRUE))|>
  ungroup()|>
  arrange(geographic_area, teer, `Job Openings`)|>
  unite(two_digit, broad, teer, sep=": ")|>
  SharedData$new(~geographic_area, group="region1")

shared_demand_occ <- demand_occ|>
  ungroup()|>
  arrange(geographic_area, broad, teer, `Job Openings`)|>
  SharedData$new(~interaction(geographic_area, broad, teer))

#shareddata objects for job openings by industry


```

```{js}
function remove_all_option() {
  document.getElementById("region").getElementsByClassName("selectized")[0].selectize.removeOption("");
  document.getElementById("teer").getElementsByClassName("selectized")[0].selectize.removeOption("");
  document.getElementById("broad").getElementsByClassName("selectized")[0].selectize.removeOption("");
  document.getElementById("region_both").getElementsByClassName("selectized")[0].selectize.removeOption("");
}
window.onload = remove_all_option;
```

Job Openings: broad occupation
===================================== 

Inputs {.sidebar}
-------------------------------------

```{r}
filter_select(
  id = "region",
  label = "Select a region:",
  sharedData = shared_for_pie,
  ~geographic_area,
  selected = "British Columbia",
  multiple = FALSE
)
```

 
Column {data-width=500}
-------------------------------------

### As a whole

```{r}
shared_for_pie|>
  plot_ly( 
        labels = ~name, 
        values = ~round(value), 
        type = 'pie'
        )
```   
 
### By broad NOC
    
```{r}
shared_broad|>
  barplot_by("broad", cat_order="trace")
``` 

### By TEER
    
```{r}
shared_teer|>
  barplot_by("teer", cat_order = "trace")
``` 


Column {data-width=700}
-------------------------------------

### By first 2 digits of NOC
    
```{r}
shared_two|>
  barplot_by("two_digit", cat_order = "trace")
```

Job Openings: narrow occupation
===========================================================

Inputs {.sidebar}
-------------------------------------

```{r}
filter_select(
  id = "region_both",
  label = "Select a region:",
  sharedData = shared_demand_occ,
  ~geographic_area,
  selected = "British Columbia",
  multiple = FALSE
)

filter_select(
  id = "broad",
  label = "Select a broad NOC category:",
  sharedData = shared_demand_occ,
  ~broad,
  selected = "Sales and service occupations",
  multiple = FALSE
)

filter_select(
  id = "teer",
  label = "Select a TEER category:",
  sharedData = shared_demand_occ,
  ~teer,
  selected = "5 No Formal Education",
  multiple = FALSE
)

```

Column
-------------------------------------

### Individual Occupations:

```{r}
shared_demand_occ|>
  barplot_by("description", "trace")
```

Job Openings: Industry
================================================

Inputs {.sidebar}
-------------------------------------

```{r}
# filter_select(
#   id = "demand_agg",
#   label = "Select an aggregate industry",
#   sharedData = shared_demand_ind,
#   ~aggregate_industry,
#   selected = "Health Care And Social Assistance",
#   multiple = FALSE
# )
```
 
Column 
-------------------------------------

### By Aggregate Industry

```{r}
# demand_ind|>
#   filter(geographic_area=="British Columbia")|>
#   group_by(aggregate_industry, name)|>
#   summarize(value=sum(value, na.rm=TRUE))|>
#   barplot_by("aggregate_industry")
```



Column 
-------------------------------------

### As a whole

```{r}

```

### Individual Industries:

```{r}
# barplot_by(shared_demand_ind, "industry", "trace")
```

Employment: Occupation
=========================================================

Column 
-------------------------------------

### Current employment

```{r}
# emp_by_two|>
#   arrange(current_employment)|>
#   barplot("current_employment")
```


Column 
-------------------------------------

### Ten year growth rates

```{r}
# emp_by_two|>
#   arrange(ten_year_growth)|>
#   barplot("ten_year_growth", format=scales::percent, accuracy=.1, tickformat=".1%")
```



Column  {data-width=350}
-------------------------------------

### Current employment vs. Ten year growth rates 

```{r}
# emp_occ|>
#   filter(geographic_area=="British Columbia")|>
#   group_by(description)|>
#   nest()|>
#   mutate(current_employment=map_dbl(data, get_current),
#          ten_year_growth=map_dbl(data, get_cagr))|>
#   plot_ly(x = ~current_employment, 
#           y = ~ten_year_growth, 
#           type = 'scatter', 
#           mode = 'markers',
#           marker = list(size = 5, color = lmo_colours[2], opacity=.5),
#           hovertext = ~paste0(
#             description,
#             "\n Current Employment: ",
#             scales::comma(current_employment, accuracy=1),
#             "\n Ten year growth rate: ",
#             scales::percent(ten_year_growth, accuracy=.1)),
#           hoverinfo = 'text',  
#           textposition = "none"
#           ) %>%
#   layout(xaxis = list(title = "Current Employment", 
#                       type = 'log',
#                       tickvals = 10^(1:5),  # Custom tick values
#                       ticktext = c("10", "100", "1,000", "10,000", "100,000")),
#          yaxis = list(title = "10 year growth rate",
#                       tickformat=".1%"))
```

Employment: Industry
================================================

Column 
-------------------------------------

### Current employment

```{r}
# emp_agg|>
#   arrange(current_employment)|>
#   barplot("current_employment", yvar="description")
```


Column 
-------------------------------------

### Ten year growth rates

```{r}
# emp_agg|>
#   arrange(ten_year_growth)|>
#   barplot("ten_year_growth", yvar="description", format=scales::percent, accuracy=.1, tickformat=".1%")
```

Column  {data-width=350}
-------------------------------------

### Current employment vs. Ten year growth rates

```{r}
# emp_ind|>
#   filter(geographic_area=="British Columbia")|>
#   group_by(industry)|>
#   nest()|>
#   mutate(current_employment=map_dbl(data, get_current),
#          ten_year_growth=map_dbl(data, get_cagr))|>
#   plot_ly(x = ~current_employment, 
#           y = ~ten_year_growth, 
#           type = 'scatter', 
#           mode = 'markers',
#           marker = list(size = 5, color = lmo_colours[2]),
#           hovertext = ~paste0(
#             industry,
#             "\n Current Employment: ",
#             scales::comma(current_employment, accuracy=1),
#             "\n Ten year growth rate: ",
#             scales::percent(ten_year_growth, accuracy=.1)),
#           hoverinfo = 'text',  
#           textposition = "none"
#           ) %>%
#   layout(xaxis = list(title = "Current Employment", 
#                       type = 'log',
#                       tickvals = 10^(1:5),  # Custom tick values
#                       ticktext = c("10", "100", "1,000", "10,000", "100,000")),
#          yaxis = list(title = "10 year growth rate",
#                       tickformat=".1%"))
```


